#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Standart, System and Third Party
from threading import Thread

# ROS
import rospy

# Robonomics communication
from robonomics_msgs.msg import Offer, Demand, Result
from ethereum_common.msg import Address, UInt256
from ethereum_common.srv import Accounts, BlockNumber
from ipfs_common.msg import Multihash
from ipfs_common.ipfs_rosbag import IpfsRosBag

from offsetting_agent.footprint import get_emission_factor, calc_footprint, get_vcu_price


class TraderNode:

    DAI_PRICE = 1   # $1

    def __init__(self):
        rospy.init_node('trader')
        rospy.loginfo('Launching trader node...')

        rospy.wait_for_service('/eth/current_block')
        rospy.wait_for_service('/eth/accounts')
        self.accounts = rospy.ServiceProxy('/eth/accounts', Accounts)()
        rospy.loginfo(str(self.accounts)) # AIRA ethereum addresses

        self.MODEL = rospy.get_param("~model")
        self.TOKEN = rospy.get_param("~token")

        rospy.Subscriber('/liability/infochan/incoming/demand', Demand, self.on_incoming_demand)

        self.signing_offer = rospy.Publisher('/liability/infochan/eth/signing/offer', Offer, queue_size=128)
        self.signing_result = rospy.Publisher('/liability/infochan/eth/signing/result', Result, queue_size=128)

        rospy.loginfo('Trader node is ready!')

    def on_incoming_demand(self, demand: Demand):
        rospy.loginfo('Incoming demand...\n{}'.format(demand))
        if demand.model.multihash == self.MODEL and demand.token.address == self.TOKEN:
            rospy.loginfo('For my model and token!')
            if demand.cost.uint256 == '0':      # Calculate the price and publish offer
                price = self.calculate_price(demand.objective)
                if price == 0:  # if price is still 0, then there was an error
                    self.send_result(demand)
                else:
                    self.make_offer(demand, UInt256(str(price)))
        else:
            rospy.loginfo('It does not fit my model or token, skip it.')

    def calculate_price(self, objective: Multihash) -> int:
        rospy.loginfo("The demand is with 0 price; Calculating...")
        bag = IpfsRosBag(multihash=objective)
        items = bag.messages

        emission_factor = get_emission_factor(items['/geo'][0].data)
        kilogram_of_co2 = calc_footprint(float(items['/power_kwh'][0].data), emission_factor)
        # ton_of_co2 = int(kilogram_of_co2 / 1000)
        # rospy.loginfo("Ton of CO2 {}".format(ton_of_co2))
        rospy.loginfo("Kg of CO2 {}".format(kilogram_of_co2))
        if kilogram_of_co2 != 0:
            vcu_price = get_vcu_price()
            dai_price = self.DAI_PRICE
            price = int(round(vcu_price / dai_price, 2) * 10**15) * kilogram_of_co2
        else:
            price = int(0)
        return price

    def send_result(self, demand: Demand):
        res = Result()
        res.liability = demand.sender
        res.result = demand.objective
        res.success = False

        rospy.loginfo(res)
        self.signing_result.publish(res)

    def get_deadline(self) -> UInt256:
        lifetime = int(rospy.get_param('~order_lifetime'))
        deadline = rospy.ServiceProxy('/eth/current_block', BlockNumber)().number + lifetime
        return UInt256(str(deadline))

    def make_offer(self, demand: Demand, cost: UInt256):
        rospy.loginfo('Making offer...')

        offer = Offer()
        offer.model = Multihash(self.MODEL)
        offer.objective = demand.objective
        offer.token = Address(self.TOKEN)
        offer.cost = cost
        offer.lighthouse = demand.lighthouse
        offer.validator = demand.validator
        offer.lighthouseFee = UInt256("0")
        offer.deadline = self.get_deadline()

        self.signing_offer.publish(offer)
        rospy.loginfo(offer)

    def spin(self):
        rospy.spin()

if __name__ == '__main__':
    TraderNode().spin()
